openapi: 3.0.0
info:
  title: Loan Matching API
  version: 1.0.0
  description: API for matching a buyer to qualified loan products based on income and age.

paths:
  /loan-match:
    post:
      summary: Match buyer to qualified loan products
      operationId: matchLoanProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - age
                - monthly_income
                - products
              properties:
                age:
                  type: integer
                  minimum: 18
                  maximum: 65
                  example: 30
                monthly_income:
                  type: number
                  minimum: 1000
                  example: 30000
                products:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required:
                      - code
                      - name
                      - tcp
                      - interest_rate
                      - max_term_years
                      - max_loanable_percent
                      - disposable_income_multiplier
                    properties:
                      code:
                        type: string
                        example: P750
                      name:
                        type: string
                        example: RDG750
                      tcp:
                        type: number
                        example: 750000
                      interest_rate:
                        type: number
                        format: float
                        example: 0.0625
                      max_term_years:
                        type: integer
                        example: 20
                      max_loanable_percent:
                        type: number
                        example: 0.95
                      disposable_income_multiplier:
                        type: number
                        example: 0.35
      responses:
        '200':
          description: A list of matched loan products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    qualified:
                      type: boolean
                      example: true
                    product_code:
                      type: string
                      example: P750
                    monthly_amortization:
                      type: number
                      example: 5452.00
                    income_required:
                      type: number
                      example: 15577.14
                    suggested_equity:
                      type: number
                      example: 0.0
                    income_gap:
                      type: number
                      example: 0.0
                    reason:
                      type: string
                      example: Sufficient disposable income
        '422':
          description: Validation error
